# Generated by Django 4.2.3 on 2023-08-08 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, unique=True, verbose_name='Category Name')),
                ('category_slug', models.SlugField(blank=True, max_length=100, verbose_name='Category Slug')),
                ('category_image', models.ImageField(blank=True, null=True, upload_to='Category_Images', verbose_name='Category Image')),
                ('category_desc', models.TextField(verbose_name='Category Description')),
                ('category_created_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_name', models.CharField(max_length=100, unique=True)),
                ('quantity_desc', models.CharField(blank=True, max_length=250)),
                ('quantity_created_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_name', models.CharField(max_length=100, unique=True)),
                ('size_name_desc', models.CharField(blank=True, max_length=250)),
                ('size_created_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, unique=True)),
                ('product_short_desc', models.CharField(max_length=250)),
                ('product_long_desc', models.TextField()),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='Product_images')),
                ('product_price', models.FloatField(default=0)),
                ('product_created_at', models.DateField(auto_now=True)),
                ('product_id', models.CharField(blank=True, max_length=100, verbose_name='Product id auto generated')),
                ('product_sell_count', models.BigIntegerField(default=0)),
                ('Quantity', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='product.quantity', verbose_name='Quantities')),
                ('Size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.size', verbose_name='Product Size')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category', verbose_name='Category')),
            ],
        ),
    ]
