# Generated by Django 4.2.3 on 2023-08-15 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_amount_order_order_amount_order_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedproduct',
            name='order_date',
            field=models.DateField(auto_now=True),
        ),
    ]
